### ISSUE TITLE
UPC-E incorrect

### ISSUE THREAD

**Issue by Arduino1987** [tecnickcom/tc-lib-barcode#38]
I have generate UPC-E for 06141939 code in three different variations which is all valid, but scanner doesn't recognize it. Valid barcode should begin with two short bars, but generated has three.:

614193
![image](https://user-images.githubusercontent.com/19413411/54929676-a35e7300-4f1e-11e9-8650-03ceba054a37.png)

0614193
![image](https://user-images.githubusercontent.com/19413411/54929473-4793ea00-4f1e-11e9-9799-47ad03dab639.png)

06141939
![image](https://user-images.githubusercontent.com/19413411/54929612-8629a480-4f1e-11e9-85ac-26419963a9cd.png)

valid barcode generated on [https://barcode.tec-it.com/en/UPCE?data=04252614](https://barcode.tec-it.com/en/UPCE?data=04252614):
![image](https://user-images.githubusercontent.com/19413411/54930571-2b914800-4f20-11e9-87dd-fcfc767a12c5.png)

my code:
```
$svgContent = new Com\Tecnick\Barcode\Barcode()
            ->getBarcodeObj('UPCE', '614193', -8, 480, 'black')
            ->setBackgroundColor('white')
            ->getSvgCode();
```

**Comment by Arduino1987** [comment]
same issue with old library [https://github.com/tecnickcom/TCPDF](https://github.com/tecnickcom/TCPDF)
but then I have added fix from [this](https://github.com/milon/barcode/issues/27) issue to old library it generate UPCE properly for 6-digit codes.

**Comment by nicolaasuni** [comment]
This should be fixed on the latest version:
https://github.com/tecnickcom/tc-lib-barcode/commit/2f6a691bae5d4cb15fceddaad4bbfc82621a2422

**Comment by Arduino1987** [comment]
Thank you!

It's OK for 614193 now, 
![image](https://user-images.githubusercontent.com/19413411/57287871-108a2a00-70c1-11e9-978b-1f2ea2d059cc.png)

but still not correct for 0614193 and 06141939 (should be the same as for 614193).
![image](https://user-images.githubusercontent.com/19413411/57287929-2c8dcb80-70c1-11e9-8d17-a95e36414d04.png)

**Comment by nicolaasuni** [comment]
The UPC-E function expect exactly 6 digits, otherwise it will assume that the code is already in UPC-A format.
