### ISSUE TITLE
php8 getPngData

### ISSUE THREAD

**Issue by ottscho** [tecnickcom/tc-lib-barcode#68]
The output under SVG and PNG are different.
PNG is wrong with php8. With php7.4 there is no problem.

Please check

**Comment by nicolaasuni** [comment]
This has been fixed in the 1.17.10 version:
https://github.com/tecnickcom/tc-lib-barcode/actions/runs/1631256491

**Comment by ottscho** [comment]
@nicolaasuni 
I have updated the version.  I can not confirm the fix. I still see the wrong barcode.
Any ideas?
thx
